### ISSUE TITLE
怎样本地开发，调试？

### ISSUE THREAD

**Issue by chenliang123** [arronKler/lime-ui#1]

**Comment by arronKler** [comment]
1. clone代码到本地之后，npm install 安装依赖项
2. 在src/packages 目录下建立自己要开发的组件，内容可参考packages 目录下的其他组件
3. 在src/index.js 文件中引入你要新开发的组件
4. 进入 docs/component 目录下建立自己要开发的组件的md文档，格式参考其他md文档
5. 在 docs/.vuepress/config.js 中引入文档
6. 在命令台运行 npm run docs:dev ，然后可以访问 localhost:8083 进入文档页边写文档边进行开发

------
其他提示：
- 8083 端口是默认配置的，可以在 docs/.vuepress/config.js 中更改
- vuepress是支持在markdown文档中写组件的，唯一需要注意的是script要在template之前。
- 其他相关的使用命令请查阅 package.json 中的配置
